package com.botmaker.sdk.internal.plugin.catalog;

import com.botmaker.plugin.api.catalog.FacadeEntry;
import com.botmaker.plugin.api.catalog.MemberEntry;
import com.botmaker.plugin.api.catalog.MemberId;
import com.botmaker.plugin.api.catalog.PaletteCatalog;
import com.botmaker.plugin.api.meta.Internal;
import com.botmaker.sdk.plugin.SdkPlugin;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The catalog's build gate: <b>a broken entry fails the build, not a menu.</b>
 *
 * <p>The catalog is generated by {@code PaletteCatalogProcessor} from the {@code @Facade} annotations in
 * this build, so a renamed or deleted member cannot leave a stale entry behind — there is nothing written
 * by hand for it to go stale in. What is still worth checking is what happens after the generated
 * {@code addAll()} has reflected over the live {@code Class<?>}: that every id names a member that really
 * exists and is really public, that it is filed under its own declaring class, that nothing is offered
 * twice, and that nothing outside {@code com.botmaker.sdk.api} — nothing a bot can write down — reached
 * the palette.
 *
 * <p>It also holds the runtime half of the rule {@code PluginSurfaceProcessor} makes a javac error: nothing
 * {@code @Internal} is offered, by its own mark or by its package's. The processor sees source, this sees the
 * built jar — which is where a generated {@code addAll()} actually decides, and where an annotation the
 * processor never saw (a member inherited, a package-info added late) would show up.
 *
 * <p>There is no per-version monotonicity check any more, because there are no per-version catalogs: what
 * an older pin may be offered is this catalog intersected with that bot's own resolved jar, which
 * {@code SdkSurfaceService} computes from bytecode. See {@link SdkPlugin}'s class comment.
 */
class ApiCatalogTest {

    private static final String API_PACKAGE = "com.botmaker.sdk.api.";

    /** Building it is itself half the test: an entry that cannot resolve throws here. */
    private static PaletteCatalog catalog() {
        return Catalog.build();
    }

    @Test
    @DisplayName("the catalog builds and is not empty")
    void catalogBuilds() {
        assertFalse(catalog().isEmpty(),
                "no facade was catalogued: is @Facade missing, or did the processor not run?");
    }

    @Test
    @DisplayName("every entry resolves to a public member of its own facade")
    void everyEntryResolves() {
        for (FacadeEntry facade : catalog().facades()) {
            for (MemberEntry member : facade.members()) {
                MemberId id = member.id();
                assertSame(facade.type(), id.declaringClass(),
                        id + " is filed under " + facade.qualifiedName());
                Method resolved = resolve(id);
                assertTrue(resolved != null, id + " names no method of " + facade.qualifiedName());
                assertTrue(Modifier.isPublic(resolved.getModifiers()), id + " is not public");
            }
        }
    }

    @Test
    @DisplayName("only types a bot can write down are catalogued")
    void everyFacadeIsPublicApi() {
        for (FacadeEntry facade : catalog().facades()) {
            assertTrue(Modifier.isPublic(facade.type().getModifiers()),
                    facade.qualifiedName() + " is not public");
            assertTrue(facade.qualifiedName().startsWith(API_PACKAGE),
                    facade.qualifiedName() + " is not under " + API_PACKAGE
                            + "; a bot cannot write that name down, so it cannot be offered");
        }
    }

    @Test
    @DisplayName("nothing @Internal reached the palette")
    void nothingInternalIsOffered() {
        for (FacadeEntry facade : catalog().facades()) {
            Class<?> type = facade.type();
            assertTrue(type.getAnnotation(Internal.class) == null,
                    facade.qualifiedName() + " carries both @Facade and @Internal");
            assertTrue(type.getPackage() == null || type.getPackage().getAnnotation(Internal.class) == null,
                    facade.qualifiedName() + " is in an @Internal package and does not override it");
            for (MemberEntry member : facade.members()) {
                Method resolved = resolve(member.id());
                assertTrue(resolved == null || resolved.getAnnotation(Internal.class) == null,
                        member.id() + " is @Internal and was offered anyway");
            }
        }
    }

    @Test
    @DisplayName("nothing is offered twice, and no simple name is claimed twice")
    void noDuplicates() {
        Set<String> simpleNames = new HashSet<>();
        for (FacadeEntry facade : catalog().facades()) {
            assertTrue(simpleNames.add(facade.simpleName()),
                    "two facades share the simple name " + facade.simpleName()
                            + "; the editor keys imports on it");
            Set<MemberId> seen = new HashSet<>();
            for (MemberEntry member : facade.members()) {
                assertTrue(seen.add(member.id()), member.id() + " is offered twice");
            }
        }
    }

    @Test
    @DisplayName("the plugin answers the same catalog for every pin, including none")
    void pluginIgnoresThePin() {
        SdkPlugin plugin = new SdkPlugin();
        PaletteCatalog current = plugin.catalog("1.1.0");
        assertFalse(current.isEmpty(), "an old pin must not empty the palette");
        assertSame(current, plugin.catalog("v1.1.0"));
        assertSame(current, plugin.catalog("0.0.0-SNAPSHOT"),
                "a dev pin is this very jar; refusing it would empty the palette in every dev build");
        assertSame(current, plugin.catalog("9.9.9"),
                "a bot newer than this jar is still offered this build's curation; the narrowing that"
                        + " matters is SdkSurfaceService's intersection against the bot's own jar");
        assertSame(current, plugin.catalog(null),
                "an absent pin must be total too — nothing here reads the pin at all");
    }

    // ----------------------------------------------------------------------------------------- helpers

    /** The method {@code id} names, or {@code null}. Matches on the JVM descriptor, so overloads differ. */
    private static Method resolve(MemberId id) {
        for (Method candidate : id.declaringClass().getDeclaredMethods()) {
            if (candidate.getName().equals(id.name()) && descriptorOf(candidate).equals(id.descriptor())) {
                return candidate;
            }
        }
        return null;
    }

    private static String descriptorOf(Method method) {
        StringBuilder out = new StringBuilder("(");
        for (Class<?> parameter : method.getParameterTypes()) {
            out.append(typeOf(parameter));
        }
        return out.append(')').append(typeOf(method.getReturnType())).toString();
    }

    private static String typeOf(Class<?> type) {
        if (type.isArray()) return "[" + typeOf(type.getComponentType());
        if (!type.isPrimitive()) return "L" + type.getName().replace('.', '/') + ";";
        if (type == void.class) return "V";
        if (type == boolean.class) return "Z";
        if (type == byte.class) return "B";
        if (type == char.class) return "C";
        if (type == short.class) return "S";
        if (type == int.class) return "I";
        if (type == long.class) return "J";
        if (type == float.class) return "F";
        return "D";
    }
}
