package com.botmaker.sdk.templates;

import com.botmaker.sdk.api.bot.Activity;
import com.botmaker.sdk.templates.meta.Template;
/*<STUDIO:ACTIVITY_IMPORT:1>*/
import com.botmaker.sdk.templates.activities.*;
/*</STUDIO:ACTIVITY_IMPORT:1>*/

import java.util.List;

/**
 * The activities this bot can run. GENERATED by BotMaker Studio — do not edit by hand; manage via
 * Project &rarr; Activity Flow. Each is built once here, which is also what registers it by name for
 * {@code Activity.disable("Name")}. {@link FlowDriver} routes between them using the outcome each one
 * reports; {@link #ALL} is the flat view for anything that just needs every activity.
 *
 * <p>The singletons are typed ({@code public static final Mining MINING}) rather than only living in
 * {@link #ALL}, because a flow route is built from that activity's <em>own</em> outcome enum — which
 * {@code List<Activity<?>>} erases.
 *
 * <p>REGENERATED — rewritten from this template on every change to the flow.
 */
@Template(id = "ACTIVITY_REGISTRY", kind = Template.Kind.REGENERATED, target = "ActivityRegistry.java",
        holes = {"ACTIVITY_IMPORT:1", "SINGLETONS:1", "ALL:1"})
public final class ActivityRegistry {

    /*<STUDIO:SINGLETONS:1>*/
    public static final ActivityStub EXAMPLE = new ActivityStub();
    /*</STUDIO:SINGLETONS:1>*/

    public static final List<Activity<?>> ALL = List.of(
            /*<STUDIO:ALL:1>*/
            EXAMPLE
            /*</STUDIO:ALL:1>*/);

    private ActivityRegistry() {}
}
