package com.botmaker.sdk.templates;

import com.botmaker.sdk.api.config.Wire;
import com.botmaker.sdk.templates.meta.Template;

/**
 * Which of this bot's activities are switched on. GENERATED by BotMaker Studio — do not edit by hand; manage
 * via Project &rarr; Activity Flow. The flags are loaded at startup from {@code /activities.json} on the
 * classpath. A missing file, a missing key, and a value that will not parse all fall back to {@code false} —
 * a bot never fails to start because of its own configuration file.
 *
 * <p><b>Flags only, since the file split.</b> This class used to hold the project's configured values as
 * well, in one flat namespace with the flags; they live in {@link Parameters} now, and that class says why.
 * What is left here is exactly one {@code boolean} per activity the project defines, which is what a stub's
 * {@code isEnabled()} reads — so the two holes below carry <b>generation 2</b>: same names, same syntax, and
 * a different set of things belongs between the fences.
 *
 * <p><b>Blank final, assigned in the static block — never an inline initializer.</b>
 * {@code public static final boolean MINING = true;} would make the field a JLS §4.12.4 <em>constant
 * variable</em>, which javac folds into every use site: {@code while (Activities.MINING) { … }} with a
 * constant-{@code false} flag becomes an <b>{@code unreachable statement} compile error</b>, so a bot would
 * stop compiling because its user unticked a box. Loading at runtime is what keeps that from happening, and
 * it is the reason this class reads a file at all rather than being generated with the values baked in.
 *
 * <p>REGENERATED — rewritten from this template on every change to the project's parameters. The reading
 * itself is {@link Wire}'s, in the SDK: this file says what this project stores, never how a stored string
 * becomes a {@code Duration}.
 */
@Template(id = "ACTIVITIES", kind = Template.Kind.REGENERATED, target = "Activities.java",
        holes = {"FIELDS:2", "INITS:2"})
public final class Activities {

    /*<STUDIO:FIELDS:2>*/
    /** Whether the example activity runs. One field per activity. */
    public static final boolean EXAMPLE;
    /*</STUDIO:FIELDS:2>*/

    static {
        /*<STUDIO:INITS:2>*/
        EXAMPLE = Wire.flag(Wire.one("EXAMPLE"));
        /*</STUDIO:INITS:2>*/
    }

    private Activities() {}
}
