package com.botmaker.sdk.templates;

import com.botmaker.sdk.api.config.Wire;
import com.botmaker.sdk.templates.meta.Template;
/*<STUDIO:IMPORTS:1>*/
import com.botmaker.sdk.api.interaction.Key;

import java.time.Duration;
import java.util.List;
/*</STUDIO:IMPORTS:1>*/

/**
 * Every configured value this bot reads. GENERATED by BotMaker Studio — do not edit by hand; manage via
 * Project &rarr; Parameters. Values are loaded at startup from {@code /activities.json} on the classpath. A
 * missing file, a missing key, and a value that will not parse all fall back to the type's default — a bot
 * never fails to start because of its own configuration file.
 *
 * <p><b>Blank final, assigned in the static block — never an inline initializer.</b>
 * {@code public static final boolean MINING = true;} would make the field a JLS §4.12.4 <em>constant
 * variable</em>, which javac folds into every use site: {@code while (Activities.MINING) { … }} with a
 * constant-{@code false} flag becomes an <b>{@code unreachable statement} compile error</b>, so a bot would
 * stop compiling because its user unticked a box. Loading at runtime is what keeps that from happening, and
 * it is the reason this class reads a file at all rather than being generated with the values baked in.
 *
 * <p>REGENERATED — rewritten from this template on every change to the project's parameters. The reading
 * itself is {@link Wire}'s, in the SDK: this file says what this project stores, never how a stored string
 * becomes a {@code Duration}.
 */
@Template(id = "ACTIVITIES", kind = Template.Kind.REGENERATED, target = "Activities.java",
        holes = {"IMPORTS:1", "FIELDS:1", "INITS:1"})
public final class Activities {

    /*<STUDIO:FIELDS:1>*/
    /** Whether the example activity runs. One field per activity, plus one per variable. */
    public static final boolean EXAMPLE;

    /** How long to rest between rounds. */
    public static final Duration REST;

    /** The keys this bot presses, in order. */
    public static final List<Key> HOTKEYS;
    /*</STUDIO:FIELDS:1>*/

    static {
        /*<STUDIO:INITS:1>*/
        EXAMPLE = Wire.flag(Wire.one("EXAMPLE"));
        REST = Wire.duration(Wire.one("REST"));
        HOTKEYS = Wire.many("HOTKEYS", Wire::key);
        /*</STUDIO:INITS:1>*/
    }

    private Activities() {}
}
