package com.botmaker.sdk.templates;

import com.botmaker.sdk.api.bot.Activity;
/*<STUDIO:ACTIVITY_IMPORT>*/
import com.botmaker.sdk.templates.activities.*;
/*</STUDIO:ACTIVITY_IMPORT>*/

import java.util.List;

/**
 * The activities this bot can run. GENERATED by BotMaker Studio — do not edit by hand; manage via
 * Project &rarr; Activity Flow. Each is built once here, which is also what registers it by name for
 * {@code Activity.disable("Name")}. {@link FlowDriver} routes between them using the outcome each one
 * reports; {@link #ALL} is the flat view for anything that just needs every activity.
 *
 * <p>The singletons are typed ({@code public static final Mining MINING}) rather than only living in
 * {@link #ALL}, because a flow route is built from that activity's <em>own</em> outcome enum — which
 * {@code List<Activity<?>>} erases.
 *
 * <p>REGENERATED — rewritten from this template on every change to the flow.
 */
public final class ActivityRegistry {

    /*<STUDIO:SINGLETONS>*/
    public static final ActivityStub EXAMPLE = new ActivityStub();
    /*</STUDIO:SINGLETONS>*/

    public static final List<Activity<?>> ALL = List.of(
            /*<STUDIO:ALL>*/
            EXAMPLE
            /*</STUDIO:ALL>*/);

    private ActivityRegistry() {}
}
