package com.botmaker.sdk.templates;

import com.botmaker.sdk.api.config.Wire;
import com.botmaker.sdk.templates.meta.Template;
/*<STUDIO:IMPORTS:1>*/
import com.botmaker.sdk.api.interaction.Key;

import java.time.Duration;
import java.util.List;
/*</STUDIO:IMPORTS:1>*/

/**
 * Every value this bot was configured with. GENERATED by BotMaker Studio — do not edit by hand; manage via
 * Project &rarr; Parameters. Values are loaded at startup from {@code /activities.json} on the classpath. A
 * missing file, a missing key, and a value that will not parse all fall back to the type's default — a bot
 * never fails to start because of its own configuration file.
 *
 * <p><b>Why this is not {@link Activities}.</b> The two used to be one class holding one flat namespace: an
 * activity's on/off tick and the delay that activity waits for were the same kind of thing, spelled the same
 * way, and a bot read {@code Activities.MINING} and {@code Activities.REST} without either name saying which
 * was which. They are not the same kind of thing. A flag is <em>the editor's</em> record of which activities
 * this bot runs, written by the Activity Flow and read by a stub's {@code isEnabled()}; a parameter is
 * <em>the user's</em> value, and is what the Runner offers, what a tag groups and what the expression menu
 * inserts. One namespace also meant one collision space, where naming a variable after an activity produced a
 * field declared twice.
 *
 * <p><b>Blank final, assigned in the static block — never an inline initializer.</b>
 * {@code public static final int RETRIES = 3;} would make the field a JLS §4.12.4 <em>constant variable</em>,
 * which javac folds into every use site, so the value a bot runs with would be the one it was compiled with
 * rather than the one in the file beside it. Loading at runtime is what keeps a re-run from needing a
 * re-build, and it is the reason this class reads a file at all rather than being generated with the values
 * baked in.
 *
 * <p>REGENERATED — rewritten from this template on every change to the project's parameters. The reading
 * itself is {@link Wire}'s, in the SDK: this file says what this project stores, never how a stored string
 * becomes a {@code Duration}.
 */
@Template(id = "PARAMETERS", kind = Template.Kind.REGENERATED, target = "Parameters.java",
        holes = {"IMPORTS:1", "FIELDS:1", "INITS:1"})
public final class Parameters {

    /*<STUDIO:FIELDS:1>*/
    /** How long to rest between rounds. */
    public static final Duration REST;

    /** The keys this bot presses, in order. */
    public static final List<Key> HOTKEYS;
    /*</STUDIO:FIELDS:1>*/

    static {
        /*<STUDIO:INITS:1>*/
        REST = Wire.duration(Wire.one("REST"));
        HOTKEYS = Wire.many("HOTKEYS", Wire::key);
        /*</STUDIO:INITS:1>*/
    }

    private Parameters() {}
}
